# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60816e89f27db7d41d03e9e98cc640551259af20a83370be11917bb63d81c12fa2241976493c3e34f173337b33373313bb5b022449adda62fe4d96862f88f150

test:
  secret_key_base: 3955d785a81844a1e6f3e142d3c2bcbfee25707faac716214d70ca85df29f8cd736d667c858ecbd07005652c37e3702a42b71510f1ac1740bb21108a2d63adfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
